# Generated by Django 4.2.15 on 2024-10-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_cat_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='full_name',
            field=models.CharField(default=1, editable=False, max_length=256),
            preserve_default=False,
        ),
    ]
