# Generated by Django 4.2.15 on 2024-10-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_owner_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='full_name',
        ),
    ]
