# Generated by Django 3.2 on 2024-10-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_auto_20241015_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(max_length=16),
        ),
    ]
